#!/usr/bin/env python3
# HARDENED COPY of check.py: 17 assert statements rewritten to explicit VerificationError raises.
# Mathematical content unchanged. Generated by harden.py (ast transform).
from __future__ import annotations

class VerificationError(Exception):
    """Raised when a proof-critical check fails."""

if not __debug__:
    raise RuntimeError("Verification requires an unoptimized interpreter; do not use -O or -OO.")

"""Exact Farkas replay and constant calibration for effective inflation."""
import itertools
import json
from collections import Counter
from fractions import Fraction
from pathlib import Path
HERE = Path(__file__).resolve().parent

def coefficient(diagonal: str) -> int:
    if diagonal in {'000111', '111000'}:
        return -1
    if diagonal in {'000000', '111111'}:
        return 0
    return 1

def swap(index: int) -> int:
    return 3 - index

def mapped_name(name: str, group_mask: int) -> str:
    kind = name[0]
    first, second = (int(name[1]), int(name[2]))
    if kind == 'A':
        if group_mask & 1:
            first = swap(first)
        if group_mask & 2:
            second = swap(second)
    elif kind == 'B':
        if group_mask & 1:
            first = swap(first)
        if group_mask & 4:
            second = swap(second)
    else:
        if group_mask & 2:
            first = swap(first)
        if group_mask & 4:
            second = swap(second)
    return f'{kind}{first}{second}'

def transformed(bits: str, names: list[str], group_mask: int) -> str:
    values = {}
    for name, bit in zip(names, bits):
        values[mapped_name(name, group_mask)] = bit
    return ''.join((values[name] for name in names))

def diagonal(bits: str, names: list[str], diagonal_names: list[str]) -> str:
    values = dict(zip(names, bits))
    return ''.join((values[name] for name in diagonal_names))

def main() -> int:
    data = json.loads((HERE / 'farkas.json').read_text())
    if not data['schema'] == 'effective-inflation-order2-farkas-v1':
        raise VerificationError("check failed at line 63: data['schema'] == 'effective-inflation-order2-farkas-v1'")
    if not data['inflation_order'] == 2:
        raise VerificationError("check failed at line 64: data['inflation_order'] == 2")
    names = data['variable_order']
    diagonal_names = data['diagonal_order']
    if not (len(names) == 12 and len(set(names)) == 12):
        raise VerificationError('check failed at line 67: len(names) == 12 and len(set(names)) == 12')
    if not len(diagonal_names) == 6:
        raise VerificationError('check failed at line 68: len(diagonal_names) == 6')
    orbit_sums = Counter()
    checked = 0
    for bits_tuple in itertools.product('01', repeat=12):
        bits = ''.join(bits_tuple)
        value = sum((coefficient(diagonal(transformed(bits, names, group), names, diagonal_names)) for group in range(8)))
        if not value >= 0:
            raise VerificationError('check failed at line 78: value >= 0')
        orbit_sums[value] += 1
        checked += 1
    if not checked == data['claimed_full_assignments_checked']:
        raise VerificationError("check failed at line 81: checked == data['claimed_full_assignments_checked']")
    if not min(orbit_sums) == data['claimed_minimum_orbit_sum']:
        raise VerificationError("check failed at line 82: min(orbit_sums) == data['claimed_minimum_orbit_sum']")
    if not data['claimed_group_elements'] == 8:
        raise VerificationError("check failed at line 83: data['claimed_group_elements'] == 8")
    target = {key: Fraction(value) for key, value in data['target'].items()}
    if not sum(target.values()) == 1:
        raise VerificationError('check failed at line 86: sum(target.values()) == 1')
    target_pair = {first + second: p * q for first, p in target.items() for second, q in target.items()}
    target_dual = sum((probability * coefficient(outcome) for outcome, probability in target_pair.items()))
    if not target_dual == Fraction(data['claimed_target_dual_value']):
        raise VerificationError("check failed at line 93: target_dual == Fraction(data['claimed_target_dual_value'])")
    if not target_dual == Fraction(-1, 2):
        raise VerificationError('check failed at line 94: target_dual == Fraction(-1, 2)')
    entropy_lower_bound = Fraction(3, 2) - 1
    promise = Fraction(data['regularized_kl_promise'])
    if not entropy_lower_bound == Fraction(data['certified_entropy_lower_bound']):
        raise VerificationError("check failed at line 100: entropy_lower_bound == Fraction(data['certified_entropy_lower_bound'])")
    if not entropy_lower_bound >= promise > 0:
        raise VerificationError('check failed at line 101: entropy_lower_bound >= promise > 0')
    k = 1
    while Fraction(9 + 2 * k, 2 ** k) >= promise:
        k += 1
    if not k == 7:
        raise VerificationError('check failed at line 106: k == 7')
    theoretical_order = 24 * 4 ** k
    threshold = Fraction(1, 2 ** k)
    if not Fraction(12, theoretical_order) == threshold ** 2 / 2:
        raise VerificationError('check failed at line 109: Fraction(12, theoretical_order) == threshold ** 2 / 2')
    if not Fraction(9 + 2 * k, 2 ** k) < promise:
        raise VerificationError('check failed at line 110: Fraction(9 + 2 * k, 2 ** k) < promise')
    if not 24 * 13 ** 4 == 685464:
        raise VerificationError('check failed at line 111: 24 * 13 ** 4 == 685464')
    result = {'status': 'PASS', 'calibration_order': 2, 'full_assignments_checked': checked, 'group_actions_per_assignment': 8, 'orbit_sum_histogram': dict(sorted(orbit_sums.items())), 'target_dual_value': str(target_dual), 'farkas_separation_margin': str(-target_dual), 'regularized_kl_lower_bound': str(entropy_lower_bound), 'promise': str(promise), 'dyadic_bound_k': k, 'theoretical_dyadic_order_not_materialized': theoretical_order, 'closed_bound_numerator': 685464}
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0
if __name__ == '__main__':
    raise SystemExit(main())
