#!/usr/bin/env python3
"""Mechanically harden a verifier: every `assert test, msg` becomes
`if not (test): raise VerificationError(msg)` so that proof-critical checks
survive python -O/-OO. The frozen originals are left untouched; this writes
a *_hardened.py sibling and prints the diff summary. Uses only the stdlib."""
import ast, sys, pathlib

if not __debug__:
    raise RuntimeError("Run without -O/-OO.")

HEADER = '''
class VerificationError(Exception):
    """Raised when a proof-critical check fails."""

if not __debug__:
    raise RuntimeError("Verification requires an unoptimized interpreter; do not use -O or -OO.")
'''

class Harden(ast.NodeTransformer):
    def __init__(self): self.count = 0
    def visit_Assert(self, node):
        self.count += 1
        msg = node.msg if node.msg is not None else ast.Constant(value=f"check failed at line {node.lineno}: {ast.unparse(node.test)}")
        new = ast.If(test=ast.UnaryOp(op=ast.Not(), operand=node.test),
                     body=[ast.Raise(exc=ast.Call(func=ast.Name(id="VerificationError", ctx=ast.Load()), args=[msg], keywords=[]), cause=None)],
                     orelse=[])
        return ast.copy_location(new, node)

def harden(src: pathlib.Path, dst: pathlib.Path):
    tree = ast.parse(src.read_text())
    h = Harden(); tree = h.visit(tree); ast.fix_missing_locations(tree)
    # remove any existing `if not __debug__:` blocks (they are re-added at top) -- keep them, harmless
    # hoist __future__ imports above the injected header (they must be first)
    futures = [n for n in tree.body if isinstance(n, ast.ImportFrom) and n.module == "__future__"]
    tree.body = [n for n in tree.body if not (isinstance(n, ast.ImportFrom) and n.module == "__future__")]
    fut = "\n".join(ast.unparse(f) for f in futures)
    body = ast.unparse(tree)
    text = f'#!/usr/bin/env python3\n# HARDENED COPY of {src.name}: {h.count} assert statements rewritten to explicit VerificationError raises.\n# Mathematical content unchanged. Generated by harden.py (ast transform).\n' + fut + "\n" + HEADER + "\n" + body + "\n"
    dst.write_text(text)
    return h.count

if __name__ == "__main__":
    here = pathlib.Path(__file__).resolve().parent.parent
    pairs = [
        (here/"certificates/infinity/original/verify_exact.py", here/"verifiers/verify_infinity_original_hardened.py"),
        (here/"certificates/infinity/independent/verify_independent.py", here/"verifiers/verify_infinity_independent_hardened.py"),
    ]
    for s, d in pairs:
        n = harden(s, d)
        print(f"{s.name} -> {d.name}: {n} asserts rewritten")
