#!/usr/bin/env python3
# HARDENED COPY of reconstruct.py: 0 assert statements rewritten to explicit VerificationError raises.
# Mathematical content unchanged. Generated by harden.py (ast transform).
from __future__ import annotations

class VerificationError(Exception):
    """Raised when a proof-critical check fails."""

if not __debug__:
    raise RuntimeError("Verification requires an unoptimized interpreter; do not use -O or -OO.")

"""Reconstruct the exact defect certificates and the sparse order-two LP point.

This program is deliberately separate from ``check.py``.  It derives the
order-two table by enumerating all 256 defect cubes and aggregating equal
observed assignments.  The validator treats the resulting table as an
untrusted LP vector and checks the NW equations directly.
"""
import argparse
import json
from collections import defaultdict
from fractions import Fraction
from pathlib import Path
HERE = Path(__file__).resolve().parent

def ratio(value: Fraction) -> str:
    return f'{value.numerator}/{value.denominator}'

def root_name(i: int, j: int, k: int) -> str:
    return f'D{i}{j}{k}'

def ordering(t: int) -> list[str]:
    return [f'A{i}{j}' for i in range(1, t + 1) for j in range(1, t + 1)] + [f'B{i}{k}' for i in range(1, t + 1) for k in range(1, t + 1)] + [f'C{j}{k}' for j in range(1, t + 1) for k in range(1, t + 1)]

def support(t: int, name: str) -> list[str]:
    kind, x, y = (name[0], int(name[1]), int(name[2]))
    if kind == 'A':
        return [root_name(x, y, k) for k in range(1, t + 1)]
    if kind == 'B':
        return [root_name(x, j, y) for j in range(1, t + 1)]
    return [root_name(i, x, y) for i in range(1, t + 1)]

def target_atoms(t: int) -> dict[str, str]:
    epsilon = Fraction(1, 2 * t ** 3)
    q = 1 - epsilon
    r = q ** (t - 1)
    atoms: dict[str, str] = {}
    for value in range(8):
        bits = f'{value:03b}'
        ones = bits.count('1')
        probability = q * r ** ones * (1 - r) ** (3 - ones)
        if bits == '000':
            probability += epsilon
        atoms[bits] = ratio(probability)
    return atoms

def structural_certificate(t: int) -> dict:
    epsilon = Fraction(1, 2 * t ** 3)
    q = 1 - epsilon
    r = q ** (t - 1)
    roots = [root_name(i, j, k) for i in range(1, t + 1) for j in range(1, t + 1) for k in range(1, t + 1)]
    return {'schema': 'inflation-defect-certificate-v1', 'order': t, 'root_law': {'kind': 'iid-bernoulli', 'p_one': ratio(epsilon), 'p_zero': ratio(q)}, 'r': ratio(r), 'roots': roots, 'outputs': [{'name': name, 'value_one_iff_all_zero': support(t, name)} for name in ordering(t)], 'target_atoms': target_atoms(t), 'claimed_diagonal_equations': 8 ** t, 'claimed_symmetry_generators': 3 * max(t - 1, 0)}

def observed_assignment(t: int, mask: int) -> str:
    roots = {}
    offset = 0
    for i in range(1, t + 1):
        for j in range(1, t + 1):
            for k in range(1, t + 1):
                roots[root_name(i, j, k)] = mask >> offset & 1
                offset += 1
    return ''.join(('1' if all((roots[root] == 0 for root in support(t, name))) else '0' for name in ordering(t)))

def full_lp_t2() -> dict:
    t = 2
    root_count = t ** 3
    denominator = (2 * t ** 3) ** root_count
    q_numerator = 2 * t ** 3 - 1
    weights: dict[str, int] = defaultdict(int)
    for mask in range(1 << root_count):
        defects = mask.bit_count()
        weights[observed_assignment(t, mask)] += q_numerator ** (root_count - defects)
    return {'schema': 'nw-full-lp-certificate-v1', 'order': t, 'ordering': ordering(t), 'denominator': denominator, 'implicit_unlisted_numerator': 0, 'entries': [{'assignment': assignment, 'numerator': numerator} for assignment, numerator in sorted(weights.items())]}

def corrupted_control(good: dict) -> dict:
    bad = json.loads(json.dumps(good))
    bad['schema'] = 'nw-full-lp-negative-control-v1'
    rows = {row['assignment']: row for row in bad['entries']}
    all_one = '1' * len(bad['ordering'])
    all_zero = '0' * len(bad['ordering'])
    rows[all_one]['numerator'] -= 1
    rows[all_zero]['numerator'] += 1
    bad['corruption'] = {'description': 'Move one denominator unit from the all-one atom to the all-zero atom.', 'normalization_preserved': True, 'nonnegativity_preserved': True, 'expected_rejection': 'diagonal marginal'}
    return bad

def expected_files() -> dict[Path, dict]:
    full = full_lp_t2()
    files = {HERE / f't{t}-defect.json': structural_certificate(t) for t in (1, 2, 3)}
    files[HERE / 't2-full-lp.json'] = full
    files[HERE / 't2-corrupted-negative-control.json'] = corrupted_control(full)
    return files

def encoded(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + '\n'

def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    mismatches = []
    for path, data in expected_files().items():
        text = encoded(data)
        if args.write:
            path.write_text(text)
        elif not path.exists() or path.read_text() != text:
            mismatches.append(path.name)
    if mismatches:
        print(json.dumps({'status': 'FAIL', 'mismatches': mismatches}))
        return 1
    print(json.dumps({'status': 'PASS', 'structural_orders': [1, 2, 3], 't2_nonzero_lp_coordinates': len(full_lp_t2()['entries'])}))
    return 0
if __name__ == '__main__':
    raise SystemExit(main())
